replica:
  replicaCount: 2
  livenessProbe:
    timeoutSeconds: 10
  readinessProbe:
    timeoutSeconds: 10
  persistence:
    enabled: false

master:
  livenessProbe:
    timeoutSeconds: 10
  readinessProbe:
    timeoutSeconds: 10
  persistence:
    enabled: false

auth:
  enabled: false